language: node_js
node_js:
  - "4.2"
before_script:
  - npm install -g bower
  - npm install -g gulp  
  - npm install
  - bower install
  - ./node_modules/protractor/bin/webdriver-manager update
script: 
  - gulp protractor